### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [tybalogh/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [ ] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
@tybalogh overall, nice job on this. There are a couple changes we'd like you to make before we make you `technical ready`:

* [ ] Make sure that you have only 4 attributes and that you have 4 methods for each class/class example
* [ ] For your methods, make sure that the use names that include verbs so that it is clear that they perform an action.
* [ ] Make sure to provide as much context as you can in your commit messages for the above updates

**Comment by damwhit** [comment]
And also, not something you need to do for the assessment, but you should probably change your git config according to the instructions here: http://mod0.turing.io/, because currently, your git user name is `Alan Turing`

**Comment by t-balogh** [comment]
Hi David,
Thanks for the feedback. Here are my corrections for the assessment - https://github.com/tybalogh/mod_0_skills.git

**Comment by damwhit** [comment]
@tybalogh this looks great. The only thing I'd say moving forward is to make sure you're using present tense for your method names instead of present progressive tense. ie. use the name `paint_car` instead of `painting_car`. In general, a computer executes things immediately so there is no need to name it as if it is constantly happening
